Repository Tkd-Alex/Twitch-Channel-Points-Miner-v2, pull requests merged in 2021-02, with the labels that each got.

#30 Use comma instead of period for delimiter
  README.md
  TwitchChannelPointsMiner/TwitchChannelPointsMiner.py
  TwitchChannelPointsMiner/classes/Bet.py
  TwitchChannelPointsMiner/classes/Streamer.py
  TwitchChannelPointsMiner/classes/TwitchBrowser.py
  TwitchChannelPointsMiner/classes/WebSocketsPool.py
  TwitchChannelPointsMiner/utils.py
  example.py
Labels: improvements

#36 Dedicated settings for each streamer
  README.md
  TwitchChannelPointsMiner/TwitchChannelPointsMiner.py
  TwitchChannelPointsMiner/__init__.py
  TwitchChannelPointsMiner/classes/Settings.py
  TwitchChannelPointsMiner/classes/Twitch.py
  TwitchChannelPointsMiner/classes/TwitchBrowser.py
  TwitchChannelPointsMiner/classes/TwitchWebSocket.py
  TwitchChannelPointsMiner/classes/WebSocketsPool.py
  TwitchChannelPointsMiner/classes/entities/Bet.py
  TwitchChannelPointsMiner/classes/entities/EventPrediction.py
  TwitchChannelPointsMiner/classes/entities/Message.py
  TwitchChannelPointsMiner/classes/entities/PubsubTopic.py
  TwitchChannelPointsMiner/classes/entities/Raid.py
  TwitchChannelPointsMiner/classes/entities/Stream.py
  TwitchChannelPointsMiner/classes/entities/Streamer.py
  TwitchChannelPointsMiner/logger.py
  TwitchChannelPointsMiner/utils.py
  assets/Roboto-Bold.ttf
  assets/main_screen.png
  assets/prediction.png
  assets/prediction_screen.png
  example.py
Labels: enhancement

#49 Array of ws in WebSocketsPool.py
  TwitchChannelPointsMiner/TwitchChannelPointsMiner.py
  TwitchChannelPointsMiner/classes/Twitch.py
  TwitchChannelPointsMiner/classes/TwitchWebSocket.py
  TwitchChannelPointsMiner/classes/WebSocketsPool.py
Labels: bug

#51 Multiple bet improvement: filter, stealth_mode
  README.md
  TwitchChannelPointsMiner/classes/Twitch.py
  TwitchChannelPointsMiner/classes/TwitchBrowser.py
  TwitchChannelPointsMiner/classes/TwitchLogin.py
  TwitchChannelPointsMiner/classes/WebSocketsPool.py
  TwitchChannelPointsMiner/classes/entities/Bet.py
  TwitchChannelPointsMiner/classes/entities/EventPrediction.py
  TwitchChannelPointsMiner/classes/entities/Message.py
  TwitchChannelPointsMiner/classes/entities/PubsubTopic.py
  TwitchChannelPointsMiner/classes/entities/Raid.py
  TwitchChannelPointsMiner/classes/entities/Stream.py
  TwitchChannelPointsMiner/utils.py
  example.py
Labels: enhancement

#50 Place the bet without Selenium
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
  TwitchChannelPointsMiner/TwitchChannelPointsMiner.py
  TwitchChannelPointsMiner/__init__.py
  TwitchChannelPointsMiner/classes/Twitch.py
  TwitchChannelPointsMiner/classes/TwitchBrowser.py
  TwitchChannelPointsMiner/classes/TwitchWebSocket.py
  TwitchChannelPointsMiner/classes/WebSocketsPool.py
  TwitchChannelPointsMiner/classes/entities/Stream.py
  TwitchChannelPointsMiner/classes/entities/Streamer.py
  TwitchChannelPointsMiner/constants.py
  TwitchChannelPointsMiner/constants/__init__.py
  TwitchChannelPointsMiner/constants/browser.py
  TwitchChannelPointsMiner/utils.py
  example.py
  requirements.txt
Labels: enhancement
